In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [ ]:
df = pd.read_csv("/content/FuelConsumption.csv")

In [ ]:
df

MODELYEAR   MAKE       MODEL    VEHICLECLASS  ENGINESIZE  CYLINDERS  \
0          2014  ACURA         ILX         COMPACT         2.0          4   
1          2014  ACURA         ILX         COMPACT         2.4          4   
2          2014  ACURA  ILX HYBRID         COMPACT         1.5          4   
3          2014  ACURA     MDX 4WD     SUV - SMALL         3.5          6   
4          2014  ACURA     RDX AWD     SUV - SMALL         3.5          6   
...         ...    ...         ...             ...         ...        ...   
1062       2014  VOLVO    XC60 AWD     SUV - SMALL         3.0          6   
1063       2014  VOLVO    XC60 AWD     SUV - SMALL         3.2          6   
1064       2014  VOLVO    XC70 AWD     SUV - SMALL         3.0          6   
1065       2014  VOLVO    XC70 AWD     SUV - SMALL         3.2          6   
1066       2014  VOLVO    XC90 AWD  SUV - STANDARD         3.2          6   

     TRANSMISSION FUELTYPE  FUELCONSUMPTION_CITY  FUELCONSUMPTION_HWY  \
0             AS5        Z                   9.9                  6.7   
1              M6        Z                  11.2                  7.7   
2             AV7        Z                   6.0                  5.8   
3             AS6        Z                  12.7                  9.1   
4             AS6        Z                  12.1                  8.7   
...           ...      ...                   ...                  ...   
1062          AS6        X                  13.4                  9.8   
1063          AS6        X                  13.2                  9.5   
1064          AS6        X                  13.4                  9.8   
1065          AS6        X                  12.9                  9.3   
1066          AS6        X                  14.9                 10.2   

      FUELCONSUMPTION_COMB  FUELCONSUMPTION_COMB_MPG  CO2EMISSIONS  
0                      8.5                        33           196  
1                      9.6                        29           221  
2                      5.9                        48           136  
3                     11.1                        25           255  
4                     10.6                        27           244  
...                    ...                       ...           ...  
1062                  11.8                        24           271  
1063                  11.5                        25           264  
1064                  11.8                        24           271  
1065                  11.3                        25           260  
1066                  12.8                        22           294  

[1067 rows x 13 columns]

In [ ]:
X=df[['ENGINESIZE']].values
y=df['CO2EMISSIONS']

In [ ]:
X

array([[2. ],
       [2.4],
       [1.5],
       ...,
       [3. ],
       [3.2],
       [3.2]])

In [ ]:
y

0       196
1       221
2       136
3       255
4       244
       ... 
1062    271
1063    264
1064    271
1065    260
1066    294
Name: CO2EMISSIONS, Length: 1067, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=.25,random_state=1)

In [ ]:
X_test

array([[3. ],
       [1.4],
       [2. ],
       [2. ],
       [4.6],
       [3. ],
       [2. ],
       [1.8],
       [3. ],
       [2.4],
       [2.4],
       [3. ],
       [2.4],
       [5.2],
       [2.5],
       [2.5],
       [1.6],
       [4.4],
       [3.5],
       [2.4],
       [6. ],
       [2.5],
       [3.7],
       [3.5],
       [3.7],
       [3. ],
       [1.2],
       [5.5],
       [1.6],
       [2. ],
       [3. ],
       [5.2],
       [3.5],
       [5.3],
       [4. ],
       [5.3],
       [6.2],
       [1.5],
       [4.2],
       [3.3],
       [3. ],
       [6.3],
       [2. ],
       [3.6],
       [3.7],
       [2. ],
       [1.4],
       [1.4],
       [2. ],
       [3.4],
       [1.6],
       [5.7],
       [4.3],
       [6.2],
       [2. ],
       [3.7],
       [2.5],
       [5. ],
       [3.7],
       [1.6],
       [2.4],
       [2.7],
       [2. ],
       [2. ],
       [2. ],
       [1.8],
       [3.7],
       [3.6],
       [2. ],
       [1.6],
       [2. ],
      

In [ ]:
y_test

133     274
340     200
948     196
704     161
661     320
       ... 
238     269
546     345
773     205
354     264
1041    186
Name: CO2EMISSIONS, Length: 267, dtype: int64

In [ ]:
from sklearn.linear_model import LinearRegression

In [ ]:
reg=LinearRegression()

In [ ]:
reg.fit(X_train, y_train)

LinearRegression()

In [ ]:
reg.predict(X_test)

array([242.88082083, 179.60282889, 203.33207587, 203.33207587,
       306.15881277, 242.88082083, 203.33207587, 195.42232688,
       242.88082083, 219.15157386, 219.15157386, 242.88082083,
       219.15157386, 329.88805975, 223.10644835, 223.10644835,
       187.51257789, 298.24906378, 262.65519331, 219.15157386,
       361.52705572, 223.10644835, 270.56494231, 262.65519331,
       270.56494231, 242.88082083, 171.6930799 , 341.75268324,
       187.51257789, 203.33207587, 242.88082083, 329.88805975,
       262.65519331, 333.84293425, 282.42956579, 333.84293425,
       369.43680471, 183.55770339, 290.33931479, 254.74544432,
       242.88082083, 373.39167921, 203.33207587, 266.61006781,
       270.56494231, 203.33207587, 179.60282889, 179.60282889,
       203.33207587, 258.70031882, 187.51257789, 349.66243223,
       294.29418928, 369.43680471, 203.33207587, 270.56494231,
       223.10644835, 321.97831076, 270.56494231, 187.51257789,
       219.15157386, 231.01619734, 203.33207587, 203.33

In [ ]:
y_test

133     274
340     200
948     196
704     161
661     320
       ... 
238     269
546     345
773     205
354     264
1041    186
Name: CO2EMISSIONS, Length: 267, dtype: int64

In [ ]:
reg.intercept_

124.23458594672331

In [ ]:
reg.coef_

array([39.54874496])

In [ ]:
reg.predict(X_test)

array([242.88082083, 179.60282889, 203.33207587, 203.33207587,
       306.15881277, 242.88082083, 203.33207587, 195.42232688,
       242.88082083, 219.15157386, 219.15157386, 242.88082083,
       219.15157386, 329.88805975, 223.10644835, 223.10644835,
       187.51257789, 298.24906378, 262.65519331, 219.15157386,
       361.52705572, 223.10644835, 270.56494231, 262.65519331,
       270.56494231, 242.88082083, 171.6930799 , 341.75268324,
       187.51257789, 203.33207587, 242.88082083, 329.88805975,
       262.65519331, 333.84293425, 282.42956579, 333.84293425,
       369.43680471, 183.55770339, 290.33931479, 254.74544432,
       242.88082083, 373.39167921, 203.33207587, 266.61006781,
       270.56494231, 203.33207587, 179.60282889, 179.60282889,
       203.33207587, 258.70031882, 187.51257789, 349.66243223,
       294.29418928, 369.43680471, 203.33207587, 270.56494231,
       223.10644835, 321.97831076, 270.56494231, 187.51257789,
       219.15157386, 231.01619734, 203.33207587, 203.33

In [ ]:
reg.score(X_test,y_test)

0.7633265438534859